### ISSUE TITLE
도서나루를 통해 책들의 정보를 받을때 description부분에 특수문자가 들어가네요

### ISSUE THREAD

**Issue by DongDongShin** [library-search-machine/Mysql_Search#1]
어떻게 해결해야 할지 조언 구합니다!!
![오류](https://user-images.githubusercontent.com/100353794/192140306-b813abcd-87cd-41d8-a25a-7898cd5b2135.PNG)
![json](https://user-images.githubusercontent.com/100353794/192140347-4f0c9dd1-6e46-4755-a7e7-09cd8ba75253.PNG)

**Comment by DongDongShin** [comment]
자문 자답이지만 .replaceAll("&gt;",""); ,replaceAll("&lt;",""); 을 이용하여 해결했는데 뭔가 하드 코딩 느낌이 나서 다른 효율적인 방법이 있을까요?

**Comment by Lee1231234** [comment]
StringEscapeUtils를 사용할수도 있습니다만,, 결국 xss의 취약한 이유를 생각해보면 모든 특수문자를  안받는 방식도 있습니다.
